apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
type: Opaque
data:
  SECRET_KEY: {{ randAlphaNum 50 | b64enc }}
  DATABASE_HOST: {{ .Values.database.host | b64enc }}
  DATABASE_PORT: {{ .Values.database.port | b64enc }}
  DATABASE_NAME: {{ .Values.database.name | b64enc }}
  DATABASE_USER: {{ .Values.database.user | b64enc }}
  # Password береться окремо, якщо він не порожній
  {{- if .Values.database.password }}
  DATABASE_PASSWORD: {{ .Values.database.password | b64enc }}
  {{- end }}