apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
type: Opaque
data:
  SECRET_KEY: {{ randAlphaNum 50 | b64enc }}
  DATABASE_HOST: {{ .Values.database.host | b64enc }}
  DATABASE_PORT: {{ .Values.database.port | b64enc }}
  DATABASE_NAME: {{ .Values.database.name | b64enc }}
  DATABASE_USER: {{ .Values.database.user | b64enc }}
  # DATABASE_PASSWORD має бути переданий через --set або файл секретних значень,
  # який не коммітиться в Git.
  DATABASE_PASSWORD: {{ .Values.database.password | default "change-me-manually" | b64enc }}