# Override values for kube-prometheus-stack

prometheus:
  prometheusSpec:
    # Сюди можна додати конфігурацію persistence (EBS), якщо потрібно зберігати метрики після перезапуску
    # storageSpec:
    #   volumeClaimTemplate:
    #     spec:
    #       storageClassName: ebs-sc
    #       accessModes: ["ReadWriteOnce"]
    #       resources:
    #         requests:
    #           storage: 10Gi
    
    # Додаткові налаштування збору метрик
    additionalScrapeConfigs: []

grafana:
  # Налаштування Grafana
  persistence:
    enabled: false # Встановіть true та вкажіть storageClassName для збереження дашбордів
